export const AVATAR_ADDRESS_PLACEHOLDER = Symbol("AVATAR_ADDRESS_PLACEHOLDER")

export const OMNI_BRIDGE_DATA_PLACEHOLDER = Symbol(
  "OMNI_BRIDGE_DATA_PLACEHOLDER"
)
export const OMNI_BRIDGE_RECEIVER_PLACEHOLDER = Symbol(
  "OMNI_BRIDGE_RECEIVER_PLACEHOLDER"
)
