/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RolesModifier } from "./RolesModifier";

export { RolesModifier__factory } from "./factories/RolesModifier__factory";
